### ISSUE TITLE
Float Error while querynig assets

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/zeitgeist-subsquid#96]
```
        query Assets {
          assets {
            assetId
            id
            poolId
            price
            qty
          }
        }
```

Trying this in query ndoe playground will give me:

```
{
  "errors": [
    {
      "message": "Float cannot represent non numeric value: \"NaN\"",
      "locations": [
        {
          "line": 6,
          "column": 13
        }
      ],
      "path": [
        "assets",
        33,
        "price"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "Float cannot represent non numeric value: \"NaN\"",
          "stacktrace": [
            "GraphQLError: Float cannot represent non numeric value: \"NaN\"",
            "    at GraphQLScalarType.serializeFloat [as serialize] (/root/zeitgeist-subsquid/node_modules/graphql/type/scalars.js:106:11)",
            "    at completeLeafValue (/root/zeitgeist-subsquid/node_modules/graphql/execution/execute.js:653:37)",
            "    at completeValue (/root/zeitgeist-subsquid/node_modules/graphql/execution/execute.js:578:12)",
            "    at resolveField (/root/zeitgeist-subsquid/node_modules/graphql/execution/execute.js:472:19)",
            "    at executeFields (/root/zeitgeist-subsquid/node_modules/graphql/execution/execute.js:292:18)",
            "    at collectAndExecuteSubfields (/root/zeitgeist-subsquid/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/root/zeitgeist-subsquid/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/root/zeitgeist-subsquid/node_modules/graphql/execution/execute.js:590:12)",
            "    at completeValue (/root/zeitgeist-subsquid/node_modules/graphql/execution/execute.js:556:21)",
            "    at /root/zeitgeist-subsquid/node_modules/graphql/execution/execute.js:620:25"
          ]
        }
      }
    },
```

**Comment by saboonikhil** [comment]
The fix is in place at https://processor.zeitgeist.pm/graphql via #92
